### ISSUE TITLE
No such file or directory: 'data/raw_data/2010_random_filtered.json'

### ISSUE THREAD

**Issue by GaiGJin** [shiningliang/Multi-level-Causality-Detection-Network#1]
很抱歉打扰您，我在运行中出现文件缺失的报错，
不知道能否方便告知我这个data/raw_data/2010_random_filtered.json和2010_full_filtered.json文件是如何获得？
冒昧打扰，还望海涵，期待您的回信

**Comment by shiningliang** [comment]
您好，对应论文中最后一个实验，我从SemEval-2010-Task 8中过滤出因果关系句子，full表示保留了其他关系的句子，random表示从其他关系中随机保留了与因果关系等量的句子。以此作为测试集，实验结果是random的。

**Comment by GaiGJin** [comment]
好的，十分感谢您。

**Comment by shiningliang** [comment]
您客气了

**Comment by shiningliang** [comment]
您客气了，就随便挂出来的代码，没想到居然有人发现了。

**Comment by GaiGJin** [comment]
嘿嘿嘿
