### ISSUE TITLE
请问data中为什么没有transfer_file文件

### ISSUE THREAD

**Issue by hechuan11** [shiningliang/Multi-level-Causality-Detection-Network#3]
请问运行python torch_run.py运行--prepare = True --build = True会报发现传输文件文件的错误，提供的数据集里没有2010_random_filtered.json这个文件。我是刚接触深度学习的学生，打扰老师了。

**Comment by shiningliang** [comment]
您好，请参考这个issue #1 
我也是学生，客气了

**Comment by hechuan11** [comment]
嗯嗯 那谢谢学长啦。

**Comment by hechuan11** [comment]
再冒昧问一下学长，我在运行过程中提示缺少词向量文件，所以就下载了glove6B.zip的词向量，请问学长怎么将它转换成代码中pkl格式的呢？刚接触深度学习，许多基本的东西还不是很了解。。。

**Comment by shiningliang** [comment]
> 再冒昧问一下学长，我在运行过程中提示缺少词向量文件，所以就下载了glove6B.zip的词向量，请问学长怎么将它转换成代码中pkl格式的呢？刚接触深度学习，许多基本的东西还不是很了解。。。

我的词向量是拿wikipedia自己train的。glove我在对比实验用的时候，记得是用gensim加载然后转存的，详细的自己查吧，都会用github了。。。

**Comment by hechuan11** [comment]
嗯嗯 谢谢学长啦。
